In [ ]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T

print(y)
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print("syn0:", syn0)
print("syn1:", syn1)
for j in np.arange(600):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)


In [51]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
print("X:", X)
# output dataset            
y = np.array([[0,0,1,1]]).T

print("y:", y)
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = np.random.random((3,1)) 

print("syn0:", syn0)

l1 = nonlin(np.dot(X,syn0))

print("l1:", l1)

l1_error = y - l1

print("l1_error:", l1_error)

l1_delta = l1_error * nonlin(l1,True)
print("l1_delta:", l1_delta)

syn0 += np.dot(l0.T,l1_delta)
print("syn0:", syn0)

for iter in np.arange(100000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)


X: [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
y: [[0]
 [0]
 [1]
 [1]]
syn0: [[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]
l1: [[0.50002859]
 [0.67270365]
 [0.60279781]
 [0.75721315]]
l1_error: [[-0.50002859]
 [-0.67270365]
 [ 0.39720219]
 [ 0.24278685]]
l1_delta: [[-0.12500715]
 [-0.14811148]
 [ 0.09510316]
 [ 0.04463427]]
syn0: [[ 0.55675944]
 [ 0.61684728]
 [-0.13326682]]
Output After Training:
[[0.0030176 ]
 [0.00246106]
 [0.99799165]
 [0.99753722]]


In [56]:
x = np.array([[1,2],[3,4]]) 
y = np.array([[5,6],[7,8]]) 
v = np.array([9,10]) 
w = np.array([11, 12]) 
z = np.array([[0,1],[1,0]]) 
z1 = np.array([[1,0],[0,1]]) 
z2 = np.array([[0,1],[0,1]]) 
# 백터의 내적, v[0]*w[0] + v[1]*w[1] = 219 

print(x)
print(x.T)
print(x.dot(x.T))
print (x.dot(z)) 
print (x.dot(z1)) 
print (x.dot(z2)) 
print (x.dot(np.array([[2],[2]]) )) 


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]
[[2 1]
 [4 3]]
[[1 2]
 [3 4]]
[[0 3]
 [0 7]]
[[ 6]
 [14]]
